apiVersion: v1
kind: Service
metadata:
  name: {{ include "pgbouncer.fullname" . }}
  labels:
    {{- include "pgbouncer.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "pgbouncer.selectorLabels" . | nindent 4 }}

---

{{- if .Values.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-metrics" (include "pgbouncer.fullname" .) }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/component: metrics
    {{- include "pgbouncer.labels" . | nindent 4 }}
  annotations:
    prometheus.io/port: {{ .Values.metrics.service.port | quote }}
    prometheus.io/scrape: "true"
spec:
  type: ClusterIP
  ports:
    - name: {{ .Values.metrics.service.ports.name }}
      port: {{ .Values.metrics.service.ports.port }}
      targetPort: {{ .Values.metrics.service.ports.name }}
  # The selector for pgbouncer-metrics can be the same as pgbouncer
  # Because selector targets pods, not individual containers
  selector:
    {{- include "pgbouncer.selectorLabels" . | nindent 4 }}
{{- end }}
