# To setup prometheus stack

repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

releases:
  - name: prometheus
    namespace: prometheus
    createNamespace: true
    chart: bitnami/kube-prometheus
    version: ~10.2.3
    values:
      - values/prometheus-values.yaml
