# To setup metrics-server

repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

releases:
  - name: metrics-server
    namespace: metrics-server
    createNamespace: true
    chart: bitnami/metrics-server
    version: ~7.3.0
    values:
      - values/metrics-server-values.yaml
