# To setup WordPress

repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

releases:
  - name: wordpress
    namespace: wordpress
    createNamespace: true
    chart: bitnami/wordpress
    version: ~24.1.6
    # Append .gotmpl if the yaml should be rendered
    values:
      - values/wordpress-values.yaml.gotmpl
