# Get config options from
# https://github.com/external-secrets/external-secrets/blob/main/deploy/charts/external-secrets/values.yaml
# https://artifacthub.io/packages/helm/external-secrets-operator/external-secrets

# Setup core external-secrets
replicaCount: 1

# Install custom resource definitions (CRDs)
installCRDs: true

# Set resources
resources:
  requests:
    cpu: 100m
    memory: 128Mi
    ephemeral-storage: 50Mi
  limits:
    cpu: 100m
    memory: 192Mi
    ephemeral-storage: 2Gi

# Set node affinity
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: node-type
          operator: In
          values:
          - master

# Disable webhook & cert controller
webhook:
  create: false

certController:
  create: false

# Setup service monitor
serviceMonitor:
  enabled: true
  interval: 1m
  scrapeTimeout: 40s
extendedMetricLabels: true
